### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by arindev1984** [shaileshaanand/vaccine-alarm#1]
Hi,
1. pip install -r requirements.txt did not work correctly, not all the mentioned versions are available or did not support my WSL version( Ubuntu-18.04, Python 3.6.9), so you need to mention what is the environment you have built it and successfully ran.
Some of the versions which I edited to proceed, 
click==7.1.2 (originally was 8.0.0)
pyinstaller==4.1 ( originally was 4.3), caught up here

Error: Collecting pyinstaller==4.1 (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/9e/ed/fbdad7f5d8f794c901076b814b8e9f5ce31d32c0bc3b63ddd27b61db9530/pyinstaller-4.1.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 175kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
```
      File "/tmp/pip-build-BLRoeN/pyinstaller/setup.py", line 63
        file=sys.stderr)
            ^
    SyntaxError: invalid syntax
```

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BLRoeN/pyinstaller/

Also, I observed after I ran "pip install -r requirements.txt" it had changed my installed py version to Python 2.7.17
I think for all these reasons you need to specify the build and working env of your code.
Thank you.

**Comment by shaileshaanand** [comment]
Please try it now
https://github.com/shaileshaanand/vaccine-alarm/commit/c49bb1835706fd3cf605cf0ce4581deb26a70536 should fix this
